### ISSUE TITLE
API: Create monitoring dashboard

### ISSUE THREAD

**Issue by lightenup** [equinor/oneseismic#100]
- [x] Configure Prometheus sample equinor/radix-platform#102
- [x] ~~Test integration with Azure Monitor/Dashboard~~
          *Azure does not allow anonymous export of dashboard*
- [x] Dashboard with Grafana equinor/radix-platform#115 
- [x] Deploy to Radix
- [x] Docker composer for local testing
- [x] Deploy dashboard configuration from git
- [x] Serve metrics to nonpublic port
- [x] ~~Grafana AD Authentication~~ (*Later*)
- [x] Persisting storage of metrics (*Separate Issue*) https://github.com/equinor/radix/issues/8
- [x] Deploy monitoring to separate deploy repo https://github.com/equinor/oneSeismic-deploy
